In [1]:
list_a  = [10,20,30]
# finding average of list_a with numpy

In [2]:
import numpy # numpy library first class I am excited!! well

numpy.mean(list_a)

20.0

In [3]:
import numpy as np #due to numpy is a long name we haveto give a
#alias name or varaibale name as np to write smaller
np.mean(list_a)

20.0

In [7]:
np.linspace(1,80,20)#Lineary space is a function in numpy

array([ 1.        ,  5.15789474,  9.31578947, 13.47368421, 17.63157895,
       21.78947368, 25.94736842, 30.10526316, 34.26315789, 38.42105263,
       42.57894737, 46.73684211, 50.89473684, 55.05263158, 59.21052632,
       63.36842105, 67.52631579, 71.68421053, 75.84210526, 80.        ])

In [11]:
number = [1,2,3,4,5,6]
numbernp = np.array(number)
print(type(number))
type(numbernp)

print(number)
print(numbernp)

<class 'list'>
[1, 2, 3, 4, 5, 6]
[1 2 3 4 5 6]


In [15]:
print(numbernp.min())
print(numbernp.max())
print(np.min(numbernp))

1
6
1


In [20]:
n = [4,6,7,3,4,5,7,9]
print(n)
print(type(n))
n = np.sort(n)
print(n)
print(type(n))

[4, 6, 7, 3, 4, 5, 7, 9]
<class 'list'>
[3 4 4 5 6 7 7 9]
<class 'numpy.ndarray'>


In [21]:
n = [4,6,7,3,4,5,7,9]
print(n)
print(type(n))
n = list(np.sort(n))
print(n)
print(type(n))

[4, 6, 7, 3, 4, 5, 7, 9]
<class 'list'>
[3, 4, 4, 5, 6, 7, 7, 9]
<class 'list'>
